name: CI

on: 	[push]
	[pull_request]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
		- name: Setup GIT
			uses: actions/checkout@v1
		- name: LaTeX compilation
      			uses: dante-ev/latex-action@v0.2.0
			
